### ISSUE TITLE
Exception from GET when process has no name property

### ISSUE THREAD

**Issue by pcoccoli** [opencybersecurityalliance/kestrel-lang#318]
**Describe the bug**
Kestrel raises an exception when you try to `GET` process objects from a STIX bundle that don't have the `name` property (which is not required by STIX 2.0 and invalid in STIX 2.1).

**Details of the bug**
- What is the hunt flow/script you are executing?
```
procs = GET process
        FROM file:///home/pcoccoli/github/kestrel-lang/tests/test_process_without_name.json
        WHERE pid > 4
```
- What is the command that failed?
`GET`
- What is the error message?
```
Traceback (most recent call last):
  File "/home/pcoccoli/github/firepit/firepit/sqlitestorage.py", line 157, in _do_execute
    cursor.execute(query)
sqlite3.OperationalError: no such column: procs_local.name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pcoccoli/.pyenv/versions/gh392/bin/kestrel", line 8, in <module>
    runpy.run_module('kestrel', run_name='__main__')
  File "/home/pcoccoli/.pyenv/versions/3.9.2/lib/python3.9/runpy.py", line 213, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/home/pcoccoli/.pyenv/versions/3.9.2/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pcoccoli/github/kestrel-lang/src/kestrel/__main__.py", line 59, in <module>
    outputs = session.execute(huntflow)
  File "/home/pcoccoli/github/kestrel-lang/src/kestrel/session.py", line 268, in execute
    return self._execute_ast(ast)
  File "/home/pcoccoli/github/kestrel-lang/src/kestrel/session.py", line 406, in _execute_ast
    output_var_struct, display = execute_cmd(stmt, self)
  File "/home/pcoccoli/github/kestrel-lang/src/kestrel/codegen/commands.py", line 101, in wrapper
    return func(stmt, session)
  File "/home/pcoccoli/github/kestrel-lang/src/kestrel/codegen/commands.py", line 72, in wrapper
    ret = func(stmt, session)
  File "/home/pcoccoli/github/kestrel-lang/src/kestrel/codegen/commands.py", line 321, in get
    prefetch_ret_entity_table = _filter_prefetched_process(
  File "/home/pcoccoli/github/kestrel-lang/src/kestrel/codegen/commands.py", line 641, in _filter_prefetched_process
    entity_ids = fine_grained_relational_process_filtering(
  File "/home/pcoccoli/github/kestrel-lang/src/kestrel/codegen/relations.py", line 254, in fine_grained_relational_process_filtering
    ref_processes = _query_process_with_time_and_ppid(store, local_var.entity_table)
  File "/home/pcoccoli/github/kestrel-lang/src/kestrel/codegen/relations.py", line 334, in _query_process_with_time_and_ppid
    rows = store.run_query(query).fetchall()
  File "/home/pcoccoli/github/firepit/firepit/sqlstorage.py", line 765, in run_query
    return self._query(query_text, query_values)
  File "/home/pcoccoli/github/firepit/firepit/sqlitestorage.py", line 184, in _query
    cursor = self._do_execute(query, values=values, cursor=cursor)
  File "/home/pcoccoli/github/firepit/firepit/sqlitestorage.py", line 164, in _do_execute
    raise InvalidAttr(m) from e
firepit.exceptions.InvalidAttr: invalid attribute: procs_local.name
```

**To Reproduce**
1. setup a data source: modify a bundle by removing all instances of `process:name`
2. test STIX-Shifter: n/a
3. run hunt flow: `kestrel <huntflow file>`

**Expected behavior**
No exceptions, and `procs` should contain 1 `process` object

**Environment (please complete the following information):**
- OS: RHEL 8.7
- Python version: Python 3.9.2
- Python install environment: Python virtual environment
- STIX-Shifter version: 4.6.2
- kestrel-lang version: 1.5.2

**Comment by pcoccoli** [comment]
Turns out this is fixed already in commit fe50950fa407e118672fd579c15133de721311cc
