### ISSUE TITLE
invalid datasource X at interface "stixshifter"

### ISSUE THREAD

**Issue by Res260** [opencybersecurityalliance/kestrel-lang#350]
**Describe the bug**
I get this error message when trying to follow the documentation ( https://kestrel.readthedocs.io/en/stable/tutorial.html#adding-kestrel-data-source-profiles ):
```
(kestrel) ➜  kestrel kestrel test.hf -v --debug
15:24:19 DEBUG kestrel.session Establish session with session_id: None, runtime_dir: None, store_path:None, debug_mode:True
15:24:19 DEBUG kestrel.config Loading default config file...
15:24:19 DEBUG kestrel.config User configuration file not exist.
15:24:19 DEBUG kestrel.config User configuration loaded: {}
15:24:19 DEBUG kestrel.config Updating default config with user config...
15:24:19 DEBUG kestrel.session create new session runtime_directory: /tmp/kestrel-session-1000-45ef11e6-a307-4bcb-8c20-62f7dc2b9b5a.
15:24:19 DEBUG firepit.sqlitestorage Connection to SQLite DB /tmp/kestrel-session-1000-45ef11e6-a307-4bcb-8c20-62f7dc2b9b5a/local.db successful
15:24:19 DEBUG firepit.sqlitestorage Executing query: CREATE TABLE IF NOT EXISTS "__metadata" (name TEXT, value TEXT);
15:24:19 DEBUG firepit.sqlitestorage Executing query: CREATE TABLE IF NOT EXISTS "__symtable" (name TEXT, type TEXT, appdata TEXT, UNIQUE(name));
15:24:19 DEBUG firepit.sqlitestorage Executing query: CREATE TABLE IF NOT EXISTS "__queries" (sco_id TEXT, query_id TEXT);
15:24:19 DEBUG firepit.sqlitestorage Executing query: CREATE TABLE IF NOT EXISTS "__contains" (source_ref TEXT, target_ref TEXT, x_firepit_rank, UNIQUE(source_ref, target_ref) ON CONFLICT IGNORE);
15:24:19 DEBUG firepit.sqlitestorage Executing query: CREATE TABLE IF NOT EXISTS "__columns" (otype TEXT, path TEXT, shortname TEXT, dtype TEXT, UNIQUE(otype, path));
15:24:19 DEBUG kestrel.codegen.commands Executing 'get' with statement: {'command': 'get', 'type': 'process', 'datasource': 'stixshifter://host101', 'where': <kestrel.syntax.ecgpattern.ExtCenteredGraphPattern object at 0x7f08cc7fba00>, 'timerange': None, 'output': 'newvar', 'stixpattern': "[process:name = 'svchost.exe']"}
15:24:19 DEBUG kestrel.config User configuration file found: /home/USER/.config/kestrel/stixshifter.yaml
15:24:19 DEBUG kestrel_datasource_stixshifter.config stix-shifter profiles found in config file
15:24:19 DEBUG kestrel_datasource_stixshifter.config profiles loaded: {'host101': {'connector': 'crowdstrike', 'connection': {'host': 'falcon.crowdstrike.com', 'port': 443}, 'configuration': {'auth': {'client_id': 'REDACTED', 'client_secret': 'REDACTED'}}}}
15:24:19 DEBUG kestrel.config User configuration file found: /home/USER/.config/kestrel/stixshifter.yaml
15:24:19 DEBUG kestrel_datasource_stixshifter.config either config file does not exist or no stix-shifter options found in config file. This may indicate a config syntax error if config file exists.
15:24:19 DEBUG kestrel_datasource_stixshifter.interface fast_translate enabled for: []
15:24:19 DEBUG kestrel_datasource_stixshifter.config set stix-shifter logging level: 20
15:24:19 DEBUG kestrel_datasource_stixshifter.interface prepare query with ID: 7c7ecaef-3232-4dd0-8e9f-e66bd84a3f11
15:24:19 DEBUG kestrel_datasource_stixshifter.config profile to use: {'connector': 'crowdstrike', 'connection': {'host': 'falcon.crowdstrike.com', 'port': 443}, 'configuration': {'auth': {'client_id': 'REDACTED', 'client_secret': 'REDACTED'}}}
Traceback (most recent call last):
  File "/home/USER/miniconda3/envs/kestrel/bin/kestrel", line 8, in <module>
    runpy.run_module('kestrel', run_name='__main__')
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/runpy.py", line 212, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/site-packages/kestrel/__main__.py", line 38, in <module>
    outputs = session.execute(huntflow)
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/site-packages/kestrel/session.py", line 274, in execute
    return self._execute_ast(ast)
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/site-packages/kestrel/session.py", line 424, in _execute_ast
    output_var_struct, display = execute_cmd(stmt, self)
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/site-packages/kestrel/codegen/commands.py", line 100, in wrapper
    return func(stmt, session)
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/site-packages/kestrel/codegen/commands.py", line 71, in wrapper
    ret = func(stmt, session)
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/site-packages/kestrel/codegen/commands.py", line 267, in get
    rs = session.data_source_manager.query(
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/site-packages/kestrel/datasource/manager.py", line 42, in query
    rs = asyncio.run(i.query(uri, pattern, session_id, c, store))
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/site-packages/kestrel_datasource_stixshifter/interface.py", line 187, in query
    copy.deepcopy, get_datasource_from_profiles(profile, config["profiles"])
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/site-packages/kestrel_datasource_stixshifter/config.py", line 111, in get_datasource_from_profiles
    raise InvalidDataSource(
kestrel.exceptions.InvalidDataSource: [ERROR] InvalidDataSource: invalid data source "host101" at interface "stixshifter". no host101 configuration defined
please check data source configuration.
```

**Details of the bug**
- What is the hunt flow/script you are executing?
```
newvar = GET process
         FROM stixshifter://host101
         WHERE [process:name = "svchost.exe"]
```
- What is the command that failed?
  - See above
- What is the error message?
- If it is a STIX-Shifter related issue, what is the results of STIX-Shifter translation?
  - No clue
- If it is a STIX-Shifter related issue, what is the results of STIX-Shifter transmission?
  - No Clue

**To Reproduce**
1. write file `~/.config/kestrel/stixshifter.yaml`:
```yaml
profiles:
    host101:
        connector: crowdstrike
        connection:
            host: falcon.crowdstrike.com
            port: 443
        configuration:
            auth: 
                client_id: REDACTED
                client_secret: REDACTED
```
3. Write `test.hf`:
```
newvar = GET process
         FROM stixshifter://host101
         WHERE [process:name = "svchost.exe"]
```
5. run hunt flow: `kestrel test.hf -v --debug`

**Expected behavior**
The kestrel file executes correctly.

**Screenshots**
No need

**Environment (please complete the following information):**
- OS: Windows 11 with WSL Ubuntu 22.04
- Python version: 3.10.0
- Python install environment: conda
- STIX-Shifter version: 5.3.0
- kestrel-lang version: 1.6.1

**Additional context**
This is a very vanilla ubuntu 22.04 that I installed today.

**Comment by subbyte** [comment]
Thanks for the issue report @Res260 !

Could you replace `configuration` with `config` as the third section for each profile in `stixshifter.yaml`?

**Comment by Res260** [comment]
I swear I looked at this config file for a good 30 minutes and never spotted that it was `config` and not `configuration` 💀

The error is gone. I think perhaps the error message could have been a little more precise, unsure how difficult it is to change though.

I have another kind of cryptic error now:

```
(kestrel) ➜  kestrel kestrel test.hf -v --debug
09:58:00 DEBUG kestrel.session Establish session with session_id: None, runtime_dir: None, store_path:None, debug_mode:True
09:58:00 DEBUG kestrel.config Loading default config file...
09:58:00 DEBUG kestrel.config User configuration file not exist.
09:58:00 DEBUG kestrel.config User configuration loaded: {}
09:58:00 DEBUG kestrel.config Updating default config with user config...
09:58:00 DEBUG kestrel.session create new session runtime_directory: /tmp/kestrel-session-1000-03c06b92-fb2e-4997-94c4-f0621ee75ae5.
09:58:00 DEBUG firepit.sqlitestorage Connection to SQLite DB /tmp/kestrel-session-1000-03c06b92-fb2e-4997-94c4-f0621ee75ae5/local.db successful
09:58:00 DEBUG firepit.sqlitestorage Executing query: CREATE TABLE IF NOT EXISTS "__metadata" (name TEXT, value TEXT);
09:58:00 DEBUG firepit.sqlitestorage Executing query: CREATE TABLE IF NOT EXISTS "__symtable" (name TEXT, type TEXT, appdata TEXT, UNIQUE(name));
09:58:00 DEBUG firepit.sqlitestorage Executing query: CREATE TABLE IF NOT EXISTS "__queries" (sco_id TEXT, query_id TEXT);
09:58:00 DEBUG firepit.sqlitestorage Executing query: CREATE TABLE IF NOT EXISTS "__contains" (source_ref TEXT, target_ref TEXT, x_firepit_rank, UNIQUE(source_ref, target_ref) ON CONFLICT IGNORE);
09:58:00 DEBUG firepit.sqlitestorage Executing query: CREATE TABLE IF NOT EXISTS "__columns" (otype TEXT, path TEXT, shortname TEXT, dtype TEXT, UNIQUE(otype, path));
09:58:01 DEBUG kestrel.codegen.commands Executing 'get' with statement: {'command': 'get', 'type': 'process', 'datasource': 'stixshifter://host101', 'where': <kestrel.syntax.ecgpattern.ExtCenteredGraphPattern object at 0x7f402ff8a200>, 'timerange': None, 'output': 'newvar', 'stixpattern': "[process:name = 'svchost.exe']"}
09:58:01 DEBUG kestrel.config User configuration file found: /home/USER/.config/kestrel/stixshifter.yaml
09:58:01 DEBUG kestrel_datasource_stixshifter.config stix-shifter profiles found in config file
09:58:01 DEBUG kestrel_datasource_stixshifter.config profiles loaded: {'host101': {'connector': 'crowdstrike', 'connection': {'host': 'falcon.crowdstrike.com', 'port': 443}, 'config': {'auth': {'client_id': 'REDACTED', 'client_secret': 'REDACTED'}}}}
09:58:01 DEBUG kestrel.config User configuration file found: /home/USER/.config/kestrel/stixshifter.yaml
09:58:01 DEBUG kestrel_datasource_stixshifter.config either config file does not exist or no stix-shifter options found in config file. This may indicate a config syntax error if config file exists.
09:58:01 DEBUG kestrel_datasource_stixshifter.interface fast_translate enabled for: []
09:58:01 DEBUG kestrel_datasource_stixshifter.config set stix-shifter logging level: 20
09:58:01 DEBUG kestrel_datasource_stixshifter.interface prepare query with ID: 664c17b2-b1a0-4dfc-8feb-249de13a699f
09:58:01 DEBUG kestrel_datasource_stixshifter.config profile to use: {'connector': 'crowdstrike', 'connection': {'host': 'falcon.crowdstrike.com', 'port': 443}, 'config': {'auth': {'client_id': 'REDACTED', 'client_secret': 'REDACTED'}}}
09:58:01 INFO stix_shifter_modules.crowdstrike.stix_translation.query_translator Converting STIX2 Pattern to FQLquery
09:58:01 DEBUG kestrel_datasource_stixshifter.interface STIX pattern to query: [process:name = 'svchost.exe']
09:58:01 DEBUG kestrel_datasource_stixshifter.interface translate results: {'queries': ["(((behaviors.filename: 'svchost.exe')) + behaviors.timestamp:> '2023-06-02T09:53:01.142805')"]}
09:58:01 DEBUG aiohttp_retry Attempt 1 out of 1
09:58:01 ERROR stix_shifter_utils.utils.error_response error occurred: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/USER/miniconda3/envs/kestrel/bin/kestrel", line 8, in <module>
    runpy.run_module('kestrel', run_name='__main__')
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/runpy.py", line 212, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/site-packages/kestrel/__main__.py", line 38, in <module>
    outputs = session.execute(huntflow)
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/site-packages/kestrel/session.py", line 274, in execute
    return self._execute_ast(ast)
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/site-packages/kestrel/session.py", line 424, in _execute_ast
    output_var_struct, display = execute_cmd(stmt, self)
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/site-packages/kestrel/codegen/commands.py", line 100, in wrapper
    return func(stmt, session)
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/site-packages/kestrel/codegen/commands.py", line 71, in wrapper
    ret = func(stmt, session)
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/site-packages/kestrel/codegen/commands.py", line 267, in get
    rs = session.data_source_manager.query(
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/site-packages/kestrel/datasource/manager.py", line 42, in query
    rs = asyncio.run(i.query(uri, pattern, session_id, c, store))
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/site-packages/kestrel_datasource_stixshifter/interface.py", line 267, in query
    batch_index = await transmission_produce(
  File "/home/USER/miniconda3/envs/kestrel/lib/python3.10/site-packages/kestrel_datasource_stixshifter/interface.py", line 381, in transmission_produce
    raise DataSourceError(
kestrel.exceptions.DataSourceError: [ERROR] DataSourceError: STIX-shifter transmission.results() failed with message: crowdstrike connector error => Expecting value: line 1 column 1 (char 0)
please check data source config or test the query manually.
09:58:01 ERROR asyncio Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<translation_ingest_consume() running at /home/USER/miniconda3/envs/kestrel/lib/python3.10/site-packages/kestrel_datasource_stixshifter/interface.py:399> wait_for=<Future pending cb=[Task.__wakeup()]>>
```

I have tried with two different sets of API keys, so I don't think the problem lies there. Any idea?

Thanks for your help, much appreciated.

**Comment by Res260** [comment]
Found the problem: I used the endpoint `falcon.crowdstrike.com` instead of `api.crowdstrike.com`. Hope it helps someone in the future haha
