### ISSUE TITLE
K2 Detailed Config Error

### ISSUE THREAD

**Issue by subbyte** [opencybersecurityalliance/kestrel-lang#523]
Need more detailed guards in interface config loading to test against config problems and raise exception to the user with details (so the user will understand how to fix). @pcoccoli suggested to use a single Exception type, fed with different details as payload.

One idea to help dev: try introducing an error and seeing what happens.

**Comment by pcoccoli** [comment]
This is all I see now:
```
k2 (develop) ~/github/kestrel-lang$ kestrel sds_syslog_sysmon_test.hf 
Traceback (most recent call last):
  File "/home/pcoccoli/.pyenv/versions/k2/bin/kestrel", line 8, in <module>
    sys.exit(kestrel())
  File "/home/pcoccoli/github/kestrel-lang/packages/kestrel_core/src/kestrel/cli.py", line 49, in kestrel
    outputs = session.execute(huntflow)
  File "/home/pcoccoli/github/kestrel-lang/packages/kestrel_core/src/kestrel/session.py", line 53, in execute
    return list(self.execute_to_generate(huntflow_block))
  File "/home/pcoccoli/github/kestrel-lang/packages/kestrel_core/src/kestrel/session.py", line 77, in execute_to_generate
    yield self.evaluate_instruction(ret)
  File "/home/pcoccoli/github/kestrel-lang/packages/kestrel_core/src/kestrel/session.py", line 108, in evaluate_instruction
    interface = _interface_manager[g.interface]
  File "/home/pcoccoli/github/kestrel-lang/packages/kestrel_core/src/kestrel/interface/manager.py", line 45, in __getitem__
    raise InterfaceNotFound(f"no interface loaded for scheme {scheme}")
```
There's no clue here for the user about what is misconfigured.  The actual problem is that I haven't set `table_creation_permission` in my sqlalchemy.yaml.

Enabling debug, the only relevant log lines are:
```
11:04:42 DEBUG kestrel_interface_sqlalchemy.interface SQLAlchemyInterface: loading config
11:04:42 DEBUG kestrel.config.utils User configuration file found: /home/pcoccoli/.config/kestrel/sqlalchemy.yaml
11:04:42 DEBUG kestrel.interface.manager Interface SQLAlchemyInterface not configured; ignored
```
This is very misleading.
